# Generated by Django 4.0.3 on 2022-06-18 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitems',
            old_name='Qquantity',
            new_name='quantity',
        ),
    ]
